In [3]:
import numpy as np
print("Задание №1:")
A = np.zeros((10, 10), int)
A[0::9, ::] = A[::, 0::9] = 1
print(A)

Задание №1
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [4]:
print("Задание №2:")
A = np.diag(range(1, 5), 1)
print(A)

Задание №2
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [9]:
print("Задание №3:")
A = np.random.rand(5, 10)
A1 = [A[i] - A[i].mean() for i in range(A.shape[0])]
print(A1)

Задание №3
[array([-0.27930309, -0.23399866,  0.27012691, -0.14907259,  0.24627402,
       -0.30990414,  0.33444744,  0.2206826 ,  0.18088785, -0.28014034]), array([ 0.15459115,  0.17012543, -0.35115801, -0.5493268 ,  0.21150086,
       -0.01707129,  0.11672915,  0.17784571, -0.31171376,  0.39847756]), array([ 0.20584982,  0.12641143, -0.37990882,  0.29582448,  0.06034446,
       -0.23761332,  0.19213584,  0.07614869, -0.23527353, -0.10391906]), array([ 0.07038138, -0.37491136, -0.34614096,  0.02491634,  0.34468745,
       -0.43090985,  0.26613125,  0.51358152,  0.32105609, -0.38879186]), array([-0.45246219, -0.52250903, -0.25679036,  0.41108607,  0.39761509,
        0.03709578,  0.19514028,  0.30543648, -0.25905735,  0.14444523])]


In [12]:
print("Задание №4:")
A = np.random.rand(6, 7)
print(f"\n{A}")
A[2::3, ::] = A[5::-3, ::]
print(f"\n{A}")

Задание №4

[[0.0295954  0.40757439 0.64279394 0.77534951 0.3323233  0.1053807
  0.78328381]
 [0.24544738 0.37384524 0.9647085  0.43293965 0.52329423 0.10853115
  0.8884894 ]
 [0.05467634 0.51868923 0.66171543 0.72215845 0.92725155 0.25615144
  0.50734609]
 [0.21870597 0.90734836 0.39165995 0.03388415 0.37739914 0.12487883
  0.66215394]
 [0.50747049 0.51505702 0.68142913 0.18023505 0.26139216 0.78110811
  0.80630493]
 [0.48658711 0.76242586 0.94180895 0.13813595 0.48796526 0.14181886
  0.14924863]]

[[0.0295954  0.40757439 0.64279394 0.77534951 0.3323233  0.1053807
  0.78328381]
 [0.24544738 0.37384524 0.9647085  0.43293965 0.52329423 0.10853115
  0.8884894 ]
 [0.48658711 0.76242586 0.94180895 0.13813595 0.48796526 0.14181886
  0.14924863]
 [0.21870597 0.90734836 0.39165995 0.03388415 0.37739914 0.12487883
  0.66215394]
 [0.50747049 0.51505702 0.68142913 0.18023505 0.26139216 0.78110811
  0.80630493]
 [0.05467634 0.51868923 0.66171543 0.72215845 0.92725155 0.25615144
  0.50734609]]


In [17]:
print("Задание №5:")
a = []
for i in range(4):
    a.append([])
    for j in range(6):
        a[i].append(np.random.randint(1, 9))
A = np.array(np.int32(a), int)
print(A)

Задание №5
[[6 3 7 5 7 6]
 [1 4 2 7 6 7]
 [3 2 6 4 5 6]
 [8 7 8 2 8 4]]


In [26]:
print("Задание №6:")
counter = 0
A = np.random.randint(-50, 50, size=(89, 67))
for i in range(89):
    for j in range(67):
        if A[i][j] != 0:
            counter += 1
print(counter)

Задание №6:
5898


In [35]:
print("Задание №7:")
n, m = map(int, input().split())
Z = np.zeros((n, m))
for i in range(n):
    for j in range(m):
        if (i + j) % 2 != 0:
            Z[i, j] = 1
print(A)


Задание №7:
4 4
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [40]:
print("Задание №8:")
from math import ceil
from math import floor
A = np.array([float(x) for x in input().split()])
Z = []
for i in range(len(A)):
    if A[i] < 0:
        Z.append(floor(A[i]))
    else:
        Z.append(ceil(A[i]))
print(Z)

Задание №8:
-3.5 3.5
[-4, 4]


In [46]:
print("Задание №9:")
A = np.array([int(x) for x in input().split()])
B = np.array([int(z) for z in input().split()])
Z = []

for i in range(len(A)):
    for j in range(len(B)):
        if A[i] == B[j]:
            Z.append(A[i])
Z = sorted(Z)
Z = np.unique(Z)
print(Z1)

Задание №9:
1 2 3
2 1 4
[1 2]
