Fedorova

1 задание

In [1]:
import numpy as np
arr = np.ones((10, 10))
arr[1:-1,1:-1] = 0
arr
print(arr[8:,:])

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2 задание

In [2]:
import numpy as np
arr = np.diag(np.arange(1, 5), k=1)
arr

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

3 задание

In [3]:
import numpy as np
arr=np.random.rand(3,4)
arr1=arr-arr.mean()
print(arr)
print(arr1)

[[0.08017777 0.71414696 0.60990974 0.58970918]
 [0.96251388 0.55972419 0.63729502 0.2326877 ]
 [0.71460629 0.425912   0.3407834  0.46567383]]
[[-0.44758389  0.1863853   0.08214808  0.06194752]
 [ 0.43475222  0.03196252  0.10953336 -0.29507397]
 [ 0.18684463 -0.10184966 -0.18697827 -0.06208783]]


4 задание

In [4]:
import numpy as np
с = np.random.random((6,7))
x=с.copy()
print(с)
a=с[2]
b=с[5]
x[2]=b
x[5]=a
print(x)

[[0.96058801 0.81393318 0.81023538 0.09170613 0.31944443 0.27940936
  0.04521756]
 [0.16606916 0.18321665 0.76353056 0.68507456 0.8051562  0.82974006
  0.05557484]
 [0.75185295 0.08443924 0.34315267 0.26027558 0.52207905 0.49830192
  0.18070135]
 [0.31822999 0.90277533 0.81731092 0.54770219 0.30456686 0.81265141
  0.08516536]
 [0.84557545 0.73985489 0.37160537 0.19560245 0.61478794 0.72394324
  0.97713112]
 [0.59385112 0.02779656 0.48797663 0.39803521 0.01001423 0.58318997
  0.66765761]]
[[0.96058801 0.81393318 0.81023538 0.09170613 0.31944443 0.27940936
  0.04521756]
 [0.16606916 0.18321665 0.76353056 0.68507456 0.8051562  0.82974006
  0.05557484]
 [0.59385112 0.02779656 0.48797663 0.39803521 0.01001423 0.58318997
  0.66765761]
 [0.31822999 0.90277533 0.81731092 0.54770219 0.30456686 0.81265141
  0.08516536]
 [0.84557545 0.73985489 0.37160537 0.19560245 0.61478794 0.72394324
  0.97713112]
 [0.75185295 0.08443924 0.34315267 0.26027558 0.52207905 0.49830192
  0.18070135]]


5 задание

In [5]:
import random
import numpy as np
a=[]
for i in range(5):
   a.append([random.randint(0, 100) for _ in range(5)])
b=np.array(b,dtype = np.int32)
print(type(a))
print(type (b))

<class 'list'>
<class 'numpy.ndarray'>


6 задание

In [6]:
a= np.random.randint(-50, 50, size=(89, 67))
b=0
for x in range(a.shape[0]):
  for y in range(a.shape[1]):
    if a[x, y]==0:
      b+=1
print(b)

54


7 задание

In [7]:
import numpy as np
m=int(input())
n=int(input())
z=np.ones((m,n))
for x in range(z.shape[0]):
  for y in range(z.shape[1]):
    if y%2==0 and x%2==0:
      z[x, y]=0
    elif y%2==1 and x%2==1:
      z[x, y]=0
z

2
6


array([[0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])

8 задание

In [8]:
import numpy as np
arr = np.array([0.1, -4.2, 1.7, 8.9, -36.3], float)
for i in range(len(arr)):
  if arr[i]>0: 
    arr[i]=np.ceil(arr[i])
  elif arr[i]<0: 
    arr[i]=np.floor(arr[i])
  else:
    arr[i]=0
print(arr)

[  1.  -5.   2.   9. -37.]


9 задание

In [ ]:
-