In [ ]:
import numpy
from math 
from math import floor

In [1]:
#задание 1
import numpy as np
a = np.ones((3,3))
a[1, 1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [5]:
#задание 2
a = np.zeros((5,5))
for i in range(4):
  a[i, i] = i+1
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#задание 3
X = np.random.rand(5, 10)
Y = np.array([[X[i,j] - X[i].mean() for j in range(X.shape[1])] for i in range(X.shape[0])])
print(Y)

[[ 0.45710881  0.52290839 -0.32075981  0.33954672 -0.38092536 -0.36135489
   0.26199546 -0.31884424 -0.29457037  0.0948953 ]
 [-0.07907397  0.36420434  0.25104    -0.39011264  0.26840517  0.15962293
  -0.5372033   0.24789321 -0.44937547  0.16459972]
 [-0.00954274  0.24376814 -0.20111929 -0.45694661 -0.43920354  0.4462529
   0.36595471 -0.25729267  0.20451716  0.10361194]
 [ 0.4361598   0.14701953 -0.42526683 -0.14137761  0.1220467  -0.49338197
   0.01108183  0.28163306  0.31642939 -0.25434389]
 [-0.0067484  -0.23177653 -0.32312831 -0.01271454  0.23699906 -0.2555275
   0.2654079  -0.05380509  0.09002038  0.29127303]]


In [55]:
#задание 4
a = np.array([[1, 2, 3, 4, 5, 6, 7],
              [8, 9, 10, 11, 12, 13, 14],
              [15, 16, 17, 18, 19, 20, 21],
              [22, 23, 24, 25, 26, 27, 28],
              [29, 30, 31, 32, 33, 34, 35],
              [36, 37, 38, 39, 40, 41, 42]], int)
b = a.copy()
a[5] = a[2]
a[2] = b[5]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [36 37 38 39 40 41 42]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [15 16 17 18 19 20 21]]


In [68]:
#задание 5
a = np.random.rand(5,5)
a = a.astype('int32')
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [66]:
#задание 6
a = 0
b = np.random.randint(-50, 50, size=(89, 67))
for i in range(89):
    for j in range(67):
        if b[i][j] != 0:
            a = a + 1
print(a)

5896


In [76]:
#задание 7
n, m = map(int, (input(), input()))
a = np.zeros((n, m))
for i in range(n):
    for j in range(m):
        if (i + j) % 2 != 0:
            a[i, j] = 1 
print(a)

8
8
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
