Домашняя работа 4

In [ ]:
import numpy as np
from math import ceil
from math import floor

In [2]:
#1
import numpy as np
a = np.ones((3, 3))
a[1, 1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [3]:
#2
a = np.zeros((5, 5))
for i in range(4):
  a[i, i+1] = i + 1
print(a)

[[0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]]


In [4]:
#3
X = np.random.rand(5, 10)
x = 0
for i in range(5):
  for j in range(10):
    x += X[i, j]
Y = x/50
Y

0.5076225888955309

In [5]:
#4
A = np.random.rand(6, 7)
B = A.copy()
B[5] = A[2]
B[2] = A[5]
print("Оригинальный массив", A)
print("Конечный массив", B)

Оригинальный массив [[0.36711042 0.31326142 0.21814661 0.33061227 0.43345797 0.89497476
  0.98904605]
 [0.08608805 0.34814502 0.34165629 0.48082272 0.64297129 0.77262113
  0.60017286]
 [0.47578218 0.47798658 0.09087659 0.39931058 0.92175958 0.05933429
  0.34814123]
 [0.52638192 0.86464172 0.9821484  0.50816051 0.06692862 0.34871328
  0.47410071]
 [0.02891264 0.15413466 0.16227358 0.12299524 0.89716383 0.33757467
  0.90861976]
 [0.19569757 0.88653564 0.93352245 0.1713312  0.9799283  0.88006744
  0.39640935]]
Конечный массив [[0.36711042 0.31326142 0.21814661 0.33061227 0.43345797 0.89497476
  0.98904605]
 [0.08608805 0.34814502 0.34165629 0.48082272 0.64297129 0.77262113
  0.60017286]
 [0.19569757 0.88653564 0.93352245 0.1713312  0.9799283  0.88006744
  0.39640935]
 [0.52638192 0.86464172 0.9821484  0.50816051 0.06692862 0.34871328
  0.47410071]
 [0.02891264 0.15413466 0.16227358 0.12299524 0.89716383 0.33757467
  0.90861976]
 [0.47578218 0.47798658 0.09087659 0.39931058 0.92175958 0.05

In [6]:
#5
C = np.random.rand(10, 10)
С = C.astype('int32')
print(C)

[[0.55920507 0.16664919 0.89161014 0.17547095 0.37275066 0.24457939
  0.68022056 0.30852291 0.02272926 0.76384156]
 [0.82746355 0.7266475  0.74434086 0.6217285  0.8839385  0.00562886
  0.57883735 0.2164072  0.08116538 0.28711516]
 [0.5143349  0.80185524 0.54836453 0.61310968 0.02034827 0.09482736
  0.01288097 0.92220904 0.1848752  0.13200835]
 [0.91977538 0.41409003 0.63647096 0.82718152 0.33739277 0.74850467
  0.72232831 0.59221437 0.04084879 0.83268322]
 [0.5064744  0.17746034 0.74169153 0.14779672 0.93244867 0.35516087
  0.66508721 0.19049234 0.51987369 0.30712882]
 [0.43230066 0.90082428 0.87565403 0.47543911 0.29926591 0.81409227
  0.03769915 0.06051163 0.8987304  0.28965706]
 [0.08972731 0.80943121 0.01522905 0.40965948 0.20954047 0.83321876
  0.00754406 0.71515751 0.47062876 0.1354813 ]
 [0.45874994 0.29826384 0.06501781 0.08015484 0.61344473 0.37161478
  0.97155992 0.3862662  0.74350475 0.95604247]
 [0.71328951 0.72196169 0.19729101 0.0584833  0.58753384 0.78078864
  0.33577651

In [7]:
#6
R = np.random.rand(89, 67) # не понял как диапазон задать
s = 0
for M in range(89):
  for N in range(67):
    if R[M, N] != 0:
      s += 1
print(s)

5963
