In [6]:
import numpy as np
a=np.zeros((10,10),int)
a[::,:1]=1
a[::,9:]=1
a[:1,::]=1
a[9:,::]=1
a

[1 1 1 1 1 1 1 1 1 1] [1 0 0 0 0 0 0 0 0 1] [1 0 0 0 0 0 0 0 0 1] [1 0 0 0 0 0 0 0 0 1] [1 0 0 0 0 0 0 0 0 1] [1 0 0 0 0 0 0 0 0 1] [1 0 0 0 0 0 0 0 0 1] [1 0 0 0 0 0 0 0 0 1] [1 0 0 0 0 0 0 0 0 1] [1 1 1 1 1 1 1 1 1 1]


In [23]:
import numpy as np
a=np.zeros((5,5),int)
a = np.diag(np.arange(1,5), k = 1)
a

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [28]:
X = np.random.rand(5, 10)
y=X.mean()
print(y)
for x in range(a.shape[0]):
    
    for y in range(a.shape[1]):
        X[x, y]-=y
X

0.48631450496536643
[[0.23694082 0.93893352 0.2796542  0.88812799 0.34729874 0.05607064
  0.20336038 0.53214887 0.93102261 0.01041186]
 [0.24854967 0.92581475 0.19345159 0.46499916 0.98715689 0.34084721
  0.53291414 0.91800605 0.64489411 0.73012565]
 [0.84575626 0.70935543 0.59004253 0.24826884 0.78770879 0.06993409
  0.65575917 0.2464859  0.95173548 0.09496212]
 [0.08335834 0.64055864 0.9550651  0.19111021 0.67422461 0.00186041
  0.49909126 0.559336   0.27752457 0.02145703]
 [0.79895249 0.44665805 0.18260037 0.60053688 0.2748459  0.84104016
  0.17391698 0.49480641 0.48841674 0.49962766]]


array([[ 2.36940819e-01, -6.10664825e-02, -1.72034580e+00,
        -2.11187201e+00, -3.65270126e+00,  5.60706398e-02,
         2.03360383e-01,  5.32148865e-01,  9.31022613e-01,
         1.04118640e-02],
       [ 2.48549672e-01, -7.41852482e-02, -1.80654841e+00,
        -2.53500084e+00, -3.01284311e+00,  3.40847207e-01,
         5.32914136e-01,  9.18006048e-01,  6.44894114e-01,
         7.30125645e-01],
       [ 8.45756256e-01, -2.90644566e-01, -1.40995747e+00,
        -2.75173116e+00, -3.21229121e+00,  6.99340909e-02,
         6.55759170e-01,  2.46485898e-01,  9.51735480e-01,
         9.49621203e-02],
       [ 8.33583388e-02, -3.59441360e-01, -1.04493490e+00,
        -2.80888979e+00, -3.32577539e+00,  1.86041415e-03,
         4.99091258e-01,  5.59335996e-01,  2.77524569e-01,
         2.14570252e-02],
       [ 7.98952490e-01, -5.53341947e-01, -1.81739963e+00,
        -2.39946312e+00, -3.72515410e+00,  8.41040163e-01,
         1.73916981e-01,  4.94806407e-01,  4.88416738e-01,
         4.

In [47]:
import numpy as np
X = np.random.rand(6, 7)
print(X)
print()
X[2::3, ::] = X[5::-3, ::]
print(X)

[[0.01948074 0.30001308 0.93500284 0.47637956 0.48591955 0.9298681
  0.16766616]
 [0.54517766 0.47083457 0.14339382 0.54901946 0.02835934 0.76649251
  0.32443788]
 [0.01170085 0.69884016 0.27360842 0.74388029 0.96593328 0.27685266
  0.31958063]
 [0.51154829 0.51112156 0.28717488 0.41967898 0.03377803 0.90640452
  0.64862964]
 [0.89762329 0.58587726 0.15918708 0.50207638 0.6526563  0.84171415
  0.02472539]
 [0.83350041 0.80842958 0.85931078 0.47061667 0.3547362  0.37076463
  0.99453611]]

[[0.01948074 0.30001308 0.93500284 0.47637956 0.48591955 0.9298681
  0.16766616]
 [0.54517766 0.47083457 0.14339382 0.54901946 0.02835934 0.76649251
  0.32443788]
 [0.83350041 0.80842958 0.85931078 0.47061667 0.3547362  0.37076463
  0.99453611]
 [0.51154829 0.51112156 0.28717488 0.41967898 0.03377803 0.90640452
  0.64862964]
 [0.89762329 0.58587726 0.15918708 0.50207638 0.6526563  0.84171415
  0.02472539]
 [0.01170085 0.69884016 0.27360842 0.74388029 0.96593328 0.27685266
  0.31958063]]


In [54]:
from random import randint
n, m = 5, 5
a = [[randint(1,100) for j in range(m)] for i in range(n)]
b = np.array(a, int)
b

array([[40, 72, 44,  1, 16],
       [ 6, 72,  8, 78, 59],
       [70, 33, 53, 24, 30],
       [52, 66, 25, 97,  9],
       [14, 67, 20, 13,  5]])

In [56]:
import numpy as np
a = np.random.randint(-50, 50, size=(89, 67))
d=0
for i in range(89):
    for j in range(67):
      if(a[i][j]!=0):
        d+=1
d

5898

In [58]:
a,b= map(int, input().split())
x=np.zeros((a,b))
for i in range(a):
    for j in range(b):
      if((i+j)%2==1):
        x[i][j]=1
x

10 10


array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])

In [62]:
import math as m
a = np.array([float(i) for i in input().split()])
b = []
for i in range(len(a)):
    if a[i] < 0:
        b.append(m.floor(a[i]))
    else:
        b.append(m.ceil(a[i]))
b

1 1 1 1 1 1


[1, 1, 1, 1, 1, 1]