In [41]:
import numpy as np
a = np.array([[1, 2, 3],[9, 0, 8],[7, 8, 5]], int)
for i in range(3):
  for j in range(3):
    print(a[i][j],end=' ')
  print()
print()
print(a[0,0],a[1,1],a[2,2])
print(a[0:,1])

1 2 3 
9 0 8 
7 8 5 

1 0 5
[2 0 8]


In [44]:
a = np.array([[1, 2, 3],[9, 0, 8],[7, 8, 5]], int)
print(a.flatten())
print(a.shape)
print(a)

[1 2 3 9 0 8 7 8 5]
(3, 3)
[[1 2 3]
 [9 0 8]
 [7 8 5]]


In [42]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]], int)
b=[]
for i in range(3):
  for j in range(3):
    print(a[i][j],end=' ')
  print()
print()
for i in range(3):
  for j in range(3):
    print(a[j][i],end=' ')
  print()

1 2 3 
4 5 6 
7 8 9 

1 4 7 
2 5 8 
3 6 9 


In [43]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]], int)
b=0;
c=0;
for i in range(3):
  for j in range(3):
    b=b+a[i,j]
    c=c+1;
c=b/c
print(b)
print(c)

18
2.0
