In [2]:
import numpy as np

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], int)
print(a)
print(a[0, 0])
print(a[1, 1])
print(a[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5
9


In [3]:

print(a[:, 1])

[2 5 8]


In [4]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], int)
print(a.shape)
b=a.flatten()
print(b)
print(b.shape)

(3, 3)
[1 2 3 4 5 6 7 8 9]
(9,)


In [5]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], int)
for y in range(a.shape[0]):
  print('столбец:', y)
  for x in range(a.shape[1]):
    print(a[x, y])

столбец: 0
1
4
7
столбец: 1
2
5
8
столбец: 2
3
6
9


In [6]:
sum=0
sr=0
for x in range(a.shape[0]):
  for y in range(a.shape[1]):
    sum=sum+a[x, y]
sr=sum/9
print(sum)
print(sr)

45
5.0
